openapi: 3.0.0
info:
  title: Credit Card Notifications and Alerts API
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  /payment-reminder:
    post:
      operationId: paymentReminder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/paymentReminder_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      x-content-type: application/json
      x-accepts: text/plain
  /balance-alert:
    post:
      operationId: balanceAlert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/balanceAlert_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      x-content-type: application/json
      x-accepts: text/plain
  /collection-notification:
    post:
      operationId: collectionNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/collectionNotification_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      x-content-type: application/json
      x-accepts: text/plain
  /payment-plan-proposal:
    post:
      operationId: paymentPlanProposal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/paymentPlanProposal_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      x-content-type: application/json
      x-accepts: text/plain
  /collection-agency:
    post:
      operationId: collectionAgencyInvolvement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/collectionAgencyInvolvement_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      x-content-type: application/json
      x-accepts: text/plain
  /legal-action:
    post:
      operationId: legalActionInitiation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/legalActionInitiation_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
      x-content-type: application/json
      x-accepts: text/plain
  /notifications:
    get:
      operationId: getNotifications
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
      x-accepts: application/json
  /card-details:
    get:
      operationId: getCardDetails
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCardDetails_200_response'
          description: OK
      x-accepts: application/json
components:
  schemas:
    getCardDetails_200_response:
      example:
        cardNumberPartial: cardNumberPartial
      properties:
        cardNumberPartial:
          type: string
      type: object
    legalActionInitiation_request:
      properties:
        nonPaymentStatus:
          type: string
        legalStatus:
          type: string
        cardLast4:
          maxLength: 4
          minLength: 4
          type: string
      required:
      - cardLast4
      - legalStatus
      - nonPaymentStatus
      type: object
    paymentPlanProposal_request:
      properties:
        outstandingBalance:
          type: string
        paymentPlan:
          $ref: '#/components/schemas/paymentPlanProposal_request_paymentPlan'
        cardLast4:
          maxLength: 4
          minLength: 4
          type: string
      required:
      - cardLast4
      - outstandingBalance
      - paymentPlan
      type: object
    balanceAlert_request:
      properties:
        paymentDueDate:
          format: date
          type: string
        currentDate:
          format: date
          type: string
        cardLast4:
          maxLength: 4
          minLength: 4
          type: string
      required:
      - cardLast4
      - currentDate
      - paymentDueDate
      type: object
    collectionNotification_request:
      properties:
        delinquencyStatus:
          type: string
        outstandingBalance:
          type: string
        additionalCharges:
          type: string
        cardLast4:
          maxLength: 4
          minLength: 4
          type: string
      required:
      - additionalCharges
      - cardLast4
      - delinquencyStatus
      - outstandingBalance
      type: object
    paymentPlanProposal_request_paymentPlan:
      properties:
        installmentAmount:
          type: string
        interestRate:
          type: string
        termLength:
          type: string
      type: object
    paymentReminder_request:
      properties:
        currentDate:
          format: date
          type: string
        paymentDueDate:
          format: date
          type: string
        cardLast4:
          maxLength: 4
          minLength: 4
          type: string
      required:
      - cardLast4
      - currentDate
      - paymentDueDate
      type: object
    collectionAgencyInvolvement_request:
      properties:
        previousNotifications:
          type: string
        responseStatus:
          type: string
        cardLast4:
          maxLength: 4
          minLength: 4
          type: string
      required:
      - cardLast4
      - previousNotifications
      - responseStatus
      type: object
