# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=8dac89cb33
# 
# 

# ********RoostGPT********
Feature: Upload Image for Pet

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['PETSTORE_AUTH'] }

  Scenario Outline: Upload image to pet
    Given path 'v2/pet/<petId>/uploadImage'
    And multipart field additionalMetadata = '<additionalMetadata>'
    And multipart file file =
      """
      { 
        read: '<filePath>', 
        filename: '<fileName>', 
        contentType: '<fileType>' 
      }
      """
    When method POST
    Then status 200
    And match response == '#object'
    And match response.code == '#number'
    And match response.type == '#string'
    And match response.message == '#string'

    Examples:
      | read('pet_petId_uploadImage_post.csv') |

  Scenario: Upload image with missing file
    Given path 'v2/pet/789/uploadImage'
    And multipart field additionalMetadata = 'No file'
    When method POST
    Then status 200
    And match response == '#object'
    And match response.code == '#number'
    And match response.type == '#string'
    And match response.message == '#string'
