
// ********RoostGPT********
/*
Test generated by RoostGPT for test jira-id_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=cardLast4_06136621ea
ROOST_METHOD_SIG_HASH=cardLast4_30a5c65934


Scenario 1: Valid 4-digit card number is set successfully

Details:
  TestName: validCardNumberSetSuccessfully
  Description: Verifies that the method `cardLast4` correctly assigns a valid 4-digit card number to the `cardLast4` field and returns the `CollectionNotificationRequest` instance.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Prepare a valid 4-digit card number string, e.g., "1234".
  Act: Invoke the `cardLast4` method with the prepared string.
  Assert: Check that the returned instance is the same as the original object. Verify that the `cardLast4` field contains the expected value.

Validation:
  The test ensures the correct functionality of the setter method, confirming that valid inputs properly update the field and maintain object integrity. It validates compliance with the business requirement that only 4-digit card numbers are permissible.

---

Scenario 2: Null card number handling

Details:
  TestName: nullCardNumberIsRejected
  Description: Tests the behavior when a null value is passed to the `cardLast4` method. Validates the system's handling of null inputs for a required field.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Prepare a null value for the card number.
  Act: Invoke the `cardLast4` method with null as input.
  Assert: Ensure that a `NullPointerException` is thrown or verify the behavior of the field under such circumstances (as per application logic).

Validation:
  This test verifies that required fields, like `cardLast4`, cannot be left unset and ensures robustness in handling null inputs.

---

Scenario 3: Empty card number handling

Details:
  TestName: emptyCardNumberIsRejected
  Description: Tests the behavior when an empty string is passed to the `cardLast4` method. Validates the system's handling of improperly formatted inputs.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Prepare an empty string as input for the card number.
  Act: Invoke the `cardLast4` method with an empty string.
  Assert: Check if validation mechanisms reject the input or handle it appropriately.

Validation:
  This test ensures that the application can identify and reject invalid card numbers that do not conform to the required format (4 characters).

---

Scenario 4: String length less than 4 rejection

Details:
  TestName: stringLengthLessThanFourRejected
  Description: Verifies that the method `cardLast4` rejects strings with less than 4 characters as inputs for `cardLast4`.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Prepare a string shorter than 4 characters, e.g., "123".
  Act: Invoke the `cardLast4` method with the prepared string.
  Assert: Confirm that validation mechanisms reject the input and throw a constraint-specific exception, if applicable.

Validation:
  This test enforces compliance with the format requirement, ensuring that only valid 4-character strings are accepted.

---

Scenario 5: String length greater than 4 rejection

Details:
  TestName: stringLengthGreaterThanFourRejected
  Description: Verifies that strings longer than 4 characters are rejected when passed to the `cardLast4` method.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Prepare a string longer than 4 characters, e.g., "12345".
  Act: Invoke the `cardLast4` method with the prepared string.
  Assert: Check whether validation mechanisms reject the input or whether exceptions (e.g., validation errors) are thrown.

Validation:
  This test guards against improper usage and ensures strict adherence to the 4-character format standard.

---

Scenario 6: Setting `cardLast4` does not affect other fields

Details:
  TestName: setCardLast4NoEffectOnOtherFields
  Description: Ensures that the `cardLast4` method updates only the `cardLast4` field without impacting the values of other fields, such as `delinquencyStatus`, `outstandingBalance`, and `additionalCharges`.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Set initial values for all other fields. Prepare a valid 4-digit card number string, e.g., "5678".
  Act: Invoke the `cardLast4` method to update the `cardLast4` field.
  Assert: Verify that the values of `delinquencyStatus`, `outstandingBalance`, and `additionalCharges` remain unchanged.

Validation:
  This test ensures the modular functionality of the method, confirming it only modifies the designated field while leaving other fields untouched.

---

Scenario 7: Object integrity after method call

Details:
  TestName: objectIntegrityAfterCardLast4Update
  Description: Tests that the `CollectionNotificationRequest` object retains its integrity (hashCode and equals behavior) after setting a valid value via `cardLast4`.

Execution:
  Arrange: Create a new instance of `CollectionNotificationRequest`. Prepare a valid 4-digit card number string, e.g., "7890".
  Act: Invoke the `cardLast4` method with the prepared string.
  Assert: Check that the object's hashCode and equality remain consistent, reflecting accurate updates only to the `cardLast4` field.

Validation:
  This test validates proper handling of object integrity and confirms that the object can be correctly used in collections or comparisons following the method call.

*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

class CollectionNotificationRequestCardLast4Test {

	@Test
	@Tag("valid")
	public void validCardNumberSetSuccessfully() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest();
		String validCardNumber = "1234";
		// Act
		CollectionNotificationRequest returnedRequest = request.cardLast4(validCardNumber);
		// Assert
		assertSame(request, returnedRequest, "Returned instance should be the same as the original object");
		assertEquals(validCardNumber, request.getCardLast4(), "CardLast4 field should match the valid input value");
	}

	@Test
	@Tag("invalid")
	public void nullCardNumberIsRejected() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest();
		String nullCardNumber = null;
		// Act & Assert
		assertThrows(NullPointerException.class, () -> request.cardLast4(nullCardNumber),
				"Null input should throw NullPointerException");
	}

	@Test
	@Tag("invalid")
	public void emptyCardNumberIsRejected() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest();
		String emptyCardNumber = "";
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> request.cardLast4(emptyCardNumber),
				"Empty input should throw IllegalArgumentException");
	}

	@Test
	@Tag("invalid")
	public void stringLengthLessThanFourRejected() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest();
		String shortCardNumber = "123";
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> request.cardLast4(shortCardNumber),
				"Input string shorter than 4 characters should throw IllegalArgumentException");
	}

	@Test
	@Tag("invalid")
	public void stringLengthGreaterThanFourRejected() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest();
		String longCardNumber = "12345";
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> request.cardLast4(longCardNumber),
				"Input string longer than 4 characters should throw IllegalArgumentException");
	}

	@Test
	@Tag("boundary")
	public void setCardLast4NoEffectOnOtherFields() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest("delinquent", "1000.00", "50.00",
				"0000");
		String validCardNumber = "5678";
		// Act
		request.cardLast4(validCardNumber);
		// Assert
		assertEquals("delinquent", request.getDelinquencyStatus(), "Delinquency status should remain unchanged");
		assertEquals("1000.00", request.getOutstandingBalance(), "Outstanding balance should remain unchanged");
		assertEquals("50.00", request.getAdditionalCharges(), "Additional charges should remain unchanged");
		assertEquals(validCardNumber, request.getCardLast4(), "CardLast4 field should be updated correctly");
	}

	@Test
	@Tag("boundary")
	public void objectIntegrityAfterCardLast4Update() {
		// Arrange
		CollectionNotificationRequest request = new CollectionNotificationRequest("delinquent", "1000.00", "50.00",
				"0000");
		String validCardNumber = "7890";
		// Act
		request.cardLast4(validCardNumber);
		// Assert
		CollectionNotificationRequest updatedRequest = new CollectionNotificationRequest("delinquent", "1000.00",
				"50.00", validCardNumber);
		assertEquals(request, updatedRequest, "Objects should be equal after cardLast4 update");
		assertEquals(request.hashCode(), updatedRequest.hashCode(), "Hash codes should match after cardLast4 update");
	}

}