
// ********RoostGPT********
/*
Test generated by RoostGPT for test Creditcard using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=cardLast4_d55e48d294
ROOST_METHOD_SIG_HASH=cardLast4_745c600f87

================================VULNERABILITIES================================
Vulnerability: CWE-359: Exposure of Private Information ('Privacy Violation')
Issue: The method cardLast4(String cardLast4) in the code is setting the last four digits of a card number. This can potentially lead to privacy violations if misused or if logging is not handled properly, as sensitive data may be written to logs.
Solution: Ensure that sensitive information like card details are not logged. Use encryption or tokenization for sensitive data. Also, consider using a PCI-DSS compliant solution for handling card data.

Vulnerability: CWE-319: Cleartext Transmission of Sensitive Information
Issue: If sensitive data like cardLast4 is being transmitted over networks, there is a risk of data being intercepted and read due to cleartext transmission.
Solution: Use secure communication protocols like HTTPS to ensure data encryption during transmission. Never transmit sensitive information over an insecure protocol.

Vulnerability: CWE-497: Exposure of System Data to an Unauthorized Control Sphere
Issue: The method cardLast4(String cardLast4) does not appear to have any access control in place. This could potentially allow unauthorized access to sensitive data.
Solution: Implement appropriate access control mechanisms. Ensure that only authorized users or systems can set or get sensitive data.

================================================================================
"""
Scenario 1: Verify cardLast4 method with valid 4 digit string

Details:
  TestName: testCardLast4WithValidInput
  Description: This test is designed to check the behaviour of the cardLast4 method when a valid 4 digit string is passed as an argument. The method should return a CollectionAgencyInvolvementRequest instance with the cardLast4 field updated.
Execution:
  Arrange: Create a CollectionAgencyInvolvementRequest instance. Prepare a valid 4 digit string.
  Act: Invoke cardLast4 method on the instance with the prepared string.
  Assert: Assert that returned object is an instance of CollectionAgencyInvolvementRequest and the cardLast4 field is updated with the string passed.
Validation:
  The assertion verifies that the method behaves as expected with valid input. It's important to ensure that the method can correctly update the cardLast4 field.

Scenario 2: Verify cardLast4 method with null input

Details:
  TestName: testCardLast4WithNullInput
  Description: This test is designed to check the behaviour of the cardLast4 method when a null value is passed as an argument. The method should return a CollectionAgencyInvolvementRequest instance with the cardLast4 field set to null.
Execution:
  Arrange: Create a CollectionAgencyInvolvementRequest instance.
  Act: Invoke cardLast4 method on the instance with null value.
  Assert: Assert that returned object is an instance of CollectionAgencyInvolvementRequest and the cardLast4 field is set to null.
Validation:
  The assertion verifies that the method handles null input gracefully. It's important to ensure that the method does not throw an exception and can correctly update the cardLast4 field to null.

Scenario 3: Verify cardLast4 method with string input of length not equal to 4

Details:
  TestName: testCardLast4WithInvalidLengthInput
  Description: This test is designed to check the behaviour of the cardLast4 method when a string of length not equal to 4 is passed as an argument. The method should throw a validation exception.
Execution:
  Arrange: Create a CollectionAgencyInvolvementRequest instance. Prepare a string of length not equal to 4.
  Act: Invoke cardLast4 method on the instance with the prepared string.
  Assert: Assert that a validation exception is thrown.
Validation:
  The assertion verifies that the method validates the length of the input string. It's important to ensure that the method enforces the constraint of the cardLast4 field being exactly 4 characters long.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CollectionAgencyInvolvementRequestCardLast4Test {

	@Test
	@Tag("valid")
	public void testCardLast4WithValidInput() {
		// Arrange
		CollectionAgencyInvolvementRequest collectionAgencyInvolvementRequest = new CollectionAgencyInvolvementRequest();
		String validCardLast4 = "1234";
		// Act
		CollectionAgencyInvolvementRequest result = collectionAgencyInvolvementRequest.cardLast4(validCardLast4);
		// Assert
		assertEquals(validCardLast4, result.getCardLast4());
	}

	@Test
	@Tag("invalid")
	public void testCardLast4WithNullInput() {
		// Arrange
		CollectionAgencyInvolvementRequest collectionAgencyInvolvementRequest = new CollectionAgencyInvolvementRequest();
		// Act
		CollectionAgencyInvolvementRequest result = collectionAgencyInvolvementRequest.cardLast4(null);
		// Assert
		assertNull(result.getCardLast4());
	}

	@Test
	@Tag("boundary")
	public void testCardLast4WithInvalidLengthInput() {
		// Arrange
		CollectionAgencyInvolvementRequest collectionAgencyInvolvementRequest = new CollectionAgencyInvolvementRequest();
		String invalidCardLast4 = "12345";
		// Act and Assert
		assertThrows(IllegalArgumentException.class,
				() -> collectionAgencyInvolvementRequest.cardLast4(invalidCardLast4));
	}

}