
// ********RoostGPT********
/*
Test generated by RoostGPT for test Creditcard using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=getCardLast4_55bc26ac31
ROOST_METHOD_SIG_HASH=getCardLast4_4a5c700ec4

================================VULNERABILITIES================================
Vulnerability: CWE-601: URL Redirection to Untrusted Site ('Open Redirect')
Issue: The code involves the use of java.net.URI that can be manipulated to redirect users to an untrusted site which can lead to phishing attacks or stealing of user credentials.
Solution: Always validate and sanitize the URLs. Use a list of trusted URLs to redirect users and do not allow redirection to URLs from user input directly.

Vulnerability: CWE-489: Leftover Debug Code
Issue: The method getCardLast4() does not have any debug logs, but in case it had, it could lead to exposure of sensitive information.
Solution: Ensure that no debug code or comments revealing sensitive information are left in the production code. Use a logging framework that can be configured to disable logging in production.

Vulnerability: CWE-611: Improper Restriction of XML External Entity Reference ('XXE')
Issue: The code includes the use of Jackson library for handling JSON, which can also handle XML. If not properly configured, it can lead to XML External Entity (XXE) attacks.
Solution: Ensure that the Jackson ObjectMapper is configured to prevent XXE attacks. Disable support for DTDs and external entities in XML.

================================================================================
"""
Scenario 1: Test to verify the correctness of the returned card last 4 digits

Details:
  TestName: verifyCardLast4Digits
  Description: This test is meant to check the correctness of the returned card last 4 digits. The target scenario is when the method getCardLast4() is invoked, it should return the last 4 digits of the card correctly.

Execution:
  Arrange: Create an instance of CollectionAgencyInvolvementRequest and set the cardLast4 digits using setCardLast4 method.
  Act: Invoke the getCardLast4() method.
  Assert: Use JUnit assertions to compare the returned cardLast4 digits against the expected cardLast4 digits.

Validation:
  The assertion aims to verify that the returned cardLast4 digits are correct. The expected result is the same cardLast4 digits that were set earlier. This test is significant to ensure that the cardLast4 digits are being correctly retrieved by the getCardLast4() method.

Scenario 2: Test to check if getCardLast4() handles null values

Details:
  TestName: handleNullCardLast4Digits
  Description: This test is meant to check if the getCardLast4() method can handle null values. The target scenario is when the cardLast4 digits are not set (or null), invoking getCardLast4() method should not result in a NullPointerException.

Execution:
  Arrange: Create an instance of CollectionAgencyInvolvementRequest without setting the cardLast4 digits.
  Act: Invoke the getCardLast4() method.
  Assert: Use JUnit assertions to confirm that the returned value is null.

Validation:
  The assertion aims to verify that the getCardLast4() method can handle null values without throwing a NullPointerException. This test is significant to ensure the robustness of the method against null inputs.

Scenario 3: Test to verify the size of the returned card last 4 digits

Details:
  TestName: verifyCardLast4DigitsSize
  Description: This test is meant to check the size of the returned card last 4 digits. The target scenario is when the method getCardLast4() is invoked, it should return exactly 4 digits.

Execution:
  Arrange: Create an instance of CollectionAgencyInvolvementRequest and set the cardLast4 digits using setCardLast4 method.
  Act: Invoke the getCardLast4() method.
  Assert: Use JUnit assertions to compare the size of the returned cardLast4 digits against the expected size of 4.

Validation:
  The assertion aims to verify that the returned cardLast4 digits have a size of 4. This test is significant to ensure that the cardLast4 digits are being correctly retrieved by the getCardLast4() method and the size of the returned string is as per the business requirement.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CollectionAgencyInvolvementRequestGetCardLast4Test {

	private CollectionAgencyInvolvementRequest collectionAgencyInvolvementRequest;

	@BeforeEach
	public void setup() {
		collectionAgencyInvolvementRequest = new CollectionAgencyInvolvementRequest();
	}

	@Test
	@Tag("valid")
	public void verifyCardLast4Digits() {
		// Arrange
		String expectedCardLast4 = "1234";
		collectionAgencyInvolvementRequest.setCardLast4(expectedCardLast4);
		// Act
		String actualCardLast4 = collectionAgencyInvolvementRequest.getCardLast4();
		// Assert
		assertEquals(expectedCardLast4, actualCardLast4, "The returned cardLast4 digits are not correct.");
	}

	@Test
	@Tag("boundary")
	public void handleNullCardLast4Digits() {
		// Act
		String cardLast4 = collectionAgencyInvolvementRequest.getCardLast4();
		// Assert
		assertNull(cardLast4, "The returned value is not null.");
	}

	@Test
	@Tag("valid")
	public void verifyCardLast4DigitsSize() {
		// Arrange
		String cardLast4 = "1234";
		collectionAgencyInvolvementRequest.setCardLast4(cardLast4);
		// Act
		String actualCardLast4 = collectionAgencyInvolvementRequest.getCardLast4();
		// Assert
		assertEquals(4, actualCardLast4.length(), "The size of the returned cardLast4 digits is not 4.");
	}

}