
// ********RoostGPT********
/*
Test generated by RoostGPT for test jira-id_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getCardLast4_b87f22b084
ROOST_METHOD_SIG_HASH=getCardLast4_6e6c9f4970


Scenario 1: Validate that cardLast4 contains exactly 4 characters

Details:
  TestName: validateCardLast4LengthProperly
  Description: Verify the method getCardLast4 enforces the requirement that the cardLast4 value has exactly 4 characters as specified by the @Size(min = 4, max = 4) constraint.

Execution:
  Arrange: Create an instance of PaymentReminderRequest and set the cardLast4 field to a valid string of exactly 4 characters.
  Act: Invoke the getCardLast4 method to retrieve the cardLast4 value.
  Assert: Compare the length of the returned value to ensure it is 4 and matches the constraints.

Validation:
  The assertion ensures that the cardLast4 value meets the defined length constraints. This test validates that only correctly formatted card details are used, maintaining integrity and compliance with validation rules.

*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.LocalDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class PaymentReminderRequestGetCardLast4Test {

	@Test
	@Tag("valid")
	public void validateCardLast4LengthProperly() {
		// Arrange
		String validCardLast4 = "1234"; // TODO: Replace with different valid values if
										// necessary
		PaymentReminderRequest request = new PaymentReminderRequest();
		request.setCardLast4(validCardLast4);
		// Act
		String actualCardLast4 = request.getCardLast4();
		// Assert
		assertEquals(validCardLast4, actualCardLast4, "Expected cardLast4 value to match the input, but it did not.");
		assertEquals(4, actualCardLast4.length(),
				"Expected cardLast4 value to have exactly 4 characters, but it did not.");
	}

	@Test
	@Tag("invalid")
	public void validateCardLast4LengthInvalidTooShort() {
		// Arrange
		String invalidCardLast4 = "123"; // Invalid length (less than 4)
		PaymentReminderRequest request = new PaymentReminderRequest();
		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			request.setCardLast4(invalidCardLast4);
		});
		assertEquals("cardLast4 must consist of 4 characters.", exception.getMessage());
	}

	@Test
	@Tag("invalid")
	public void validateCardLast4LengthInvalidTooLong() {
		// Arrange
		String invalidCardLast4 = "12345"; // Invalid length (more than 4)
		PaymentReminderRequest request = new PaymentReminderRequest();
		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			request.setCardLast4(invalidCardLast4);
		});
		assertEquals("cardLast4 must consist of 4 characters.", exception.getMessage());
	}

	@Test
	@Tag("boundary")
	public void validateCardLast4LengthBoundaryAtMinLimit() {
		// Arrange
		String validCardLast4 = "1234"; // Boundary case (min limit)
		PaymentReminderRequest request = new PaymentReminderRequest();
		request.setCardLast4(validCardLast4);
		// Act
		String actualCardLast4 = request.getCardLast4();
		// Assert
		assertEquals(validCardLast4, actualCardLast4,
				"Expected cardLast4 value at boundary (min limit) to match the input.");
		assertEquals(4, actualCardLast4.length(),
				"Expected cardLast4 value to have exactly 4 characters, but it did not.");
	}

	@Test
	@Tag("boundary")
	public void validateCardLast4LengthBoundaryAtMaxLimit() {
		// Arrange
		String validCardLast4 = "5678"; // Boundary case (max limit)
		PaymentReminderRequest request = new PaymentReminderRequest();
		request.setCardLast4(validCardLast4);
		// Act
		String actualCardLast4 = request.getCardLast4();
		// Assert
		assertEquals(validCardLast4, actualCardLast4,
				"Expected cardLast4 value at boundary (max limit) to match the input.");
		assertEquals(4, actualCardLast4.length(),
				"Expected cardLast4 value to have exactly 4 characters, but it did not.");
	}

	@Test
	@Tag("invalid")
	public void validateCardLast4WithNullValue() {
		// Arrange
		PaymentReminderRequest request = new PaymentReminderRequest();
		// Act & Assert
		IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
			request.setCardLast4(null);
		});
		assertEquals("cardLast4 is required and must not be null.", exception.getMessage());
	}

}