# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=9124f669d9
# 
# 

# ********RoostGPT********
Feature: Tests for /v2/pet/findByTags API Endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: karate.properties['PETSTORE_AUTH'] }

  Scenario Outline: Test successful operation with valid tags
    Given path 'v2/pet/findByTags'
    And param tags = <tags>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].category.id == '#number'
    And match each response[*].category.name == '#string'
    And match each response[*].name == '#string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].photoUrls[*] == '#string'
    And match each response[*].tags == '#[]'
    And match each response[*].tags[*].id == '#number'
    And match each response[*].tags[*].name == '#string'
    And match each response[*].status == '#string'
    Then assert response[*].status contains any(['available', 'pending', 'sold'])

    Examples:
      | read('pet_findByTags_get.csv') |

  Scenario: Test invalid operation with null tags
    Given path 'v2/pet/findByTags'
    And param tags = null
    When method GET
    Then status 400

  Scenario Outline: Test systems handle malformed tags input
    Given path 'v2/pet/findByTags'
    And param tags = <tags>
    When method GET
    Then status 400

    Examples:
      | tags           |
      | ["unexpected"] |
      | ["error"]      |
      | ["malformed"]  |

  Scenario: Ensure security configuration is being processed
    Given path 'v2/pet/findByTags'
    When method GET
    Then assert karate.properties['PETSTORE_AUTH'] != null
