# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=561990ad39
# 
# 

# ********RoostGPT********
Feature: Find Pet by ID API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get pet details by ID with valid path parameter
    Given path 'v2/pet/<petId>'
    When method GET
    Then status 200
    And match response == """ #object """
    And match response.id == "#number"
    And match response.name == "#string"
    And match response.photoUrls == """ #[]
      string """
    And match response.category.id == """ #? _ == null || #number """
    And match response.category.name == """ #? _ == null || #string """
    And match response.tags == """ #[]
      object """
    And match each response.tags[*].id == "#number"
    And match each response.tags[*].name == "#string"
    And match response.status == "#string"
    And match response.status == """ #? _ == null || _ == "available" || _ == "pending" || _ == "sold" """

    Examples:
      | petId |
      |     1 |
      |   555 |
      |  9999 |

  Scenario: Invalid ID supplied
    Given path 'v2/pet/abc'
    When method GET
    Then status 400
    And match response == """ #null """

  Scenario: Pet not found
    Given path 'v2/pet/999999'
    When method GET
    Then status 404
    And match response == """ #null """
