# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /user/logout_get for http method type GET 
# RoostTestHash=696422fb14
# 
# 

# ********RoostGPT********
Feature: User Logout API Tests
  This feature file tests the /v2/user/logout endpoint for logging out the current logged-in user session.

  Background:
    Given def urlBase = karate.properties['URL_BASE']
    And url urlBase

  Scenario: Test successful logout operation
    Given url urlBase + '/v2/user/logout'
    When method GET
    Then status 200
    And match response ==
      """
      #? _.length == 0 || typeof _ == "string" || typeof _ == "number" || typeof _ == "boolean" || typeof _ == "object" || typeof _ == "array"
      """

  Scenario: Test unsupported HTTP method - POST
    Given url urlBase + '/v2/user/logout'
    When method POST
    Then status 404

  Scenario: Test unsupported HTTP method - PUT
    Given url urlBase + '/v2/user/logout'
    When method PUT
    Then status 404

  Scenario: Test unsupported HTTP method - DELETE
    Given url urlBase + '/v2/user/logout'
    When method DELETE
    Then status 404
