# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /user/createWithArray_post for http method type POST 
# RoostTestHash=2fceff8367
# 
# 

# ********RoostGPT********
Feature: Create Users with Array Input API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Validate Create Users with Array Input API using POST method
    Given path 'v2/user/createWithArray'
    And request """<body>"""
    When method POST
    Then status 200
    And match response == '#? typeof _ == "object" || typeof _ == "null"'
    And match response.id == '#? typeof _ == "number" || _ == null'
    And match response.username == '#? typeof _ == "string" || _ == null'
    And match response.firstName == '#? typeof _ == "string" || _ == null'
    And match response.lastName == '#? typeof _ == "string" || _ == null'
    And match response.email == '#? typeof _ == "string" || _ == null'
    And match response.password == '#? typeof _ == "string" || _ == null'
    And match response.phone == '#? typeof _ == "string" || _ == null'
    And match response.userStatus == '#? typeof _ == "number" || _ == null'

    Examples:
      | read('user_createWithArray_post.csv') |
