# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /user/createWithArray_post for http method type POST 
# RoostTestHash=2fceff8367
# 
# 

# ********RoostGPT********
Feature: Test API for creating a list of users via array input

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Verify successful creation of users using array input
    Given path 'v2/user/createWithArray'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 200
    And match response == '#string'

    Examples:
      | read('user_createWithArray_post.csv') |

  Scenario: Verify failed creation due to missing required field in array input
    Given path 'v2/user/createWithArray'
    And request
      """
      [{ "username": "johndoe", "email": "john.doe@example.com" }]
      """
    When method POST
    Then status 400
    And match response == '#string'

  Scenario Outline: Verify response structure and headers for valid requests
    Given path 'v2/user/createWithArray'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 200
    And match responseHeaders['Content-Type'] == '#string'
    And match response == '#string'

    Examples:
      | read('user_createWithArray_post.csv') |

  Scenario: Verify response is an empty string for unsupported method types
    Given path 'v2/user/createWithArray'
    When method GET
    Then status 405
    And match response == ''

  Scenario: Verify response structure and headers when XML content is produced
    Given path 'v2/user/createWithArray'
    And header Accept = 'application/xml'
    And request
      """
      [{ "id": 5, "username": "lindawhite", "firstName": "Linda", "lastName": "White", "email": "linda.white@example.com", "password": "WhitePass", "phone": "+321654987", "userStatus": 5 }]
      """
    When method POST
    Then status 200
    And match responseHeaders['Content-Type'] == '#string'
    And match response == '#string'

  Scenario Outline: Verify invalid creation of users due to incorrect data type
    Given path 'v2/user/createWithArray'
    And request
      """
      <requestBody>
      """
    When method POST
    Then status 400
    And match response == '#string'

    Examples:
      | requestBody                                                                                                                                                                 |
      | [{ "id": "one", "username": true, "firstName": "Maria", "lastName": "Gomez", "email": "maria.gomez@example.com", "password": 123, "phone": false, "userStatus": "active" }] |
      | [{ "id": 6.5, "username": null, "firstName": "Chris", "lastName": "Martin", "email": "chris.martin@example.com", "password": null, "phone": null, "userStatus": -1 }]       |
