# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-plan using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /user/createWithList_post for http method type POST 
# RoostTestHash=41ad79e90d
# 
# 

# ********RoostGPT********
Feature: Test createUsersWithListInput API endpoint functionality

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Verify successful creation of users with an input list
    Given path '/v2/user/createWithList'
    And request """<inputPayload>"""
    When method POST
    Then status 200
    And match response == '#? _ == null || typeof _ == "object" || typeof _ == "array"'
    And match response == '##object'
    And match response == contains { }
    And match responseHeaders['Content-Type'] == '#string'

    Examples:
      | read('user_createWithList_post.csv') |

  Scenario: Attempt to create users with an empty body
    Given path '/v2/user/createWithList'
    And request """[]"""
    When method POST
    Then status 200
    And match response == '#? _ == null || typeof _ == "object" || typeof _ == "array"'
    And match responseHeaders['Content-Type'] == '#string'
