openapi: 3.0.2
info:
  title: Credit Card Management System API
  description: This page documents the Credit Card Management System API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /credit-card-api/details:
    get:
      parameters:
        - name: cardNumber
          in: query
          description: Credit Card number to fetch details
          required: true
          schema:
            type: string
            pattern: '^[0-9]{10}$'
      responses:
        '200':
          description: Credit card details successfully fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  dueDate:
                    type: string
                  balance:
                    type: integer
        '400':
          description: Invalid card number provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: 'Invalid card number'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: 'Access denied'
  /credit-card-api/alerts:
    post:
      parameters:
        - name: cardNumber
          in: query
          description: Credit Card number with overdue payment
          required: true
          schema:
            type: string
            pattern: '^[0-9]{10}$'
      responses:
        '200':
          description: Overdue payment alert action successfully initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: 'Call initiated'
  /credit-card-api/payments:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                CardNumber:
                  type: string
                  pattern: '^[0-9]{10}$'
                Amount:
                  type: number
      responses:
        '200':
          description: Payment successful and balance updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: 'Payment successful'
                  newBalance:
                    type: number
