openapi: 3.0.0
info:
  version: 1.0.0
  title: CardholderNotifications API
  description: A simple API to send notifications to the card holder

servers: 
  - url: http://api.cardholder-notifications.com

paths:
  /due-reminder:
     post:
       summary: Send a Due Payment Reminder
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
       responses:
         '200':
           description: 'Payment for card XXXX is due soon'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/CardholderResponse'

  /overdue-alert:
     post:
       summary: Send an Overdue Payment Alert
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
       responses:
         '200':
           description: 'Payment for card XXXX is overdue'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/CardholderResponse'

  /collection-notice:
     post:
       summary: Send a Collection Notice
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
       responses:
         '200':
           description: 'Account on card XXXX is significantly delinquent'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/CardholderResponse'

  /payment-proposal:
     post:
       summary: Send a Payment Plan Proposal
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
       responses:
         '200':
           description: 'We have a payment plan proposal for your card XXXX'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/CardholderResponse'

  /collection-agency-notice:
     post:
       summary: Send a Collection Agency Involvement Notice
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
       responses:
         '200':
           description: 'Collection agency will be involved for card XXXX'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/CardholderResponse'

  /legal-action-notice:
     post:
       summary: Send a Legal Action Initiation Notice
       requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
       responses:
         '200':
           description: 'Legal action initiated for card XXXX due to non-payment or default'
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/CardholderResponse'

components:
  schemas:
    Notification:
      type: object
      properties:
        card_last_4_digits:
          type: integer
        message:
          type: string
          description: Message to be sent to the card holder
    CardholderResponse:
      type: object
      properties:
        card_last_4_digits:
          type: integer
        message:
          type: string
          description: Message received by the card holder
      required:
        - card_last_4_digits
        - message
