# ********RoostGPT********

# Test generated by RoostGPT for test CreditCard-Karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /credit-card-api/alerts_post for http method type POST 
# RoostTestHash=ce4b87cdce
# 
# 

# ********RoostGPT********
Feature: Credit Card Alerts API

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Initiate overdue payment alert action
    Given path '/credit-card-api/alerts'
    And param cardNumber = '<cardNumber>'
    And header Authorization = authToken
    When method POST
    Then status 200
    And match response == { message: 'Call initiated' }

    Examples:
        | cardNumber |
        | 1234567890 |
        | 9876543210 |

