# ********RoostGPT********

# Test generated by RoostGPT for test CreditCard-Karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /credit-card-api/alerts_post for http method type POST 
# RoostTestHash=ce4b87cdce
# 
# 

# ********RoostGPT********
Feature: Credit Card Overdue Payment Alert

Background:
  * def authToken = karate.properties['AUTH_TOKEN']
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Overdue payment alert action initiation
  Given path '/credit-card-api/alerts'
  * param cardNumber = '<cardNumber>'
  * header Authorization = authToken
  When method get
  Then status 200
  * match response == """{"message": "Call initiated"}"""

Examples:
  | cardNumber |
  | '1234567890' |
  | '0987654321' |
